version: '2'
services:
    web:
        image: tdlm/alpine-lemp
        build: .
        ports:
            - "80:80"
        volumes:
            - ./html:/usr/share/nginx/html
        links:
            - mariadb:db
    mariadb:
        image: paintedfox/mariadb
        environment:
            - USER="user"
            - PASS="password"

